### ISSUE TITLE
[Help]: Why do you need RxDart?

### ISSUE THREAD

**Issue by chipweinberger** [tnc1997/flutter-blue-plus#2]
### What is your problem
Anything you need should already be in the utils file. If you need some other feature, just add it to the utils file.

https://github.com/chipweinberger/flutter_blue_plus/blob/master/lib/src/utils.dart

For example (already in utils file):

`Stream<T> _mergeStreams<T>(List<Stream<T>> streams) `

**Comment by chipweinberger** [comment]
As for why to not use RxDart? RxDart frequently releases new versions, and sometimes has regressions and deprecations. It's happened before.

It's more reliable to get it working once in a util file, and not change the code.

**Comment by tnc1997** [comment]
> Why do you need RxDart?

`rxdart` is used in the Linux platform implementation and avoids reproducing code that already exists in that package.

This reduces the size of the final bundle and reduces the maintenance overhead of the Linux platform implementation.

> So FBP will be stuck with whatever version of RxDart the user chooses.

The version constraint `>=0.27.0 <0.29.0` means that any version greater than 0.27.0 and less than 0.29.0 is supported.

If a developer attempts to use a version outside of this constraint then they will receive a message when `dart pub get`.

```yaml
dependencies:
  flutter:
    sdk: flutter
  flutter_blue_plus:
    git:
      url: https://github.com/tnc1997/flutter-blue-plus.git
      path: packages/flutter_blue_plus
      ref: flutter_blue_plus-v1.0.0
  rxdart: ^0.26.0
```

> Because every version of flutter_blue_plus from git depends on flutter_blue_plus_linux from git which depends on rxdart >=0.27.0 <0.29.0, every version of flutter_blue_plus from git requires rxdart >=0.27.0 <0.29.0. So, because flutter_blue_plus_example depends on both flutter_blue_plus from git and rxdart 0.26.0, version solving failed.

If the Linux platform implementation is maintained in the upstream repository then we could remove `rxdart` if desired.
